apiVersion: v1
kind: Service
metadata:
  name: {{ include "epiconnect.fullname" . }}
  labels:
    {{- include "epiconnect.webSelector" . | nindent 4 }}
    {{- include "epiconnect.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "epiconnect.webSelector" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
